# Generated by Django 6.0.4 on 2026-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('yes', 'Обязательно ✅'), ('no', 'Запрещено ❌')], max_length=5, verbose_name='Тип')),
                ('text', models.CharField(max_length=300, verbose_name='Текст правила')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('children', 'Детская группа'), ('women', 'Женская группа'), ('men', 'Мужская группа')], max_length=20, unique=True, verbose_name='Группа')),
                ('days', models.CharField(max_length=100, verbose_name='Дни недели')),
                ('time_start', models.CharField(max_length=10, verbose_name='Начало')),
                ('time_end', models.CharField(max_length=10, verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
